apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
    - nodePort: 30081
      targetPort: resultport
      port: 80
  selector:
      app: result-app
      tier: frontend
