apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result-app
    tier: frontend
spec:
  template:
     metadata:
        name: result-app
        labels:
          app: result-app
          tier: frontend
     spec:
        containers:
          - name: result-app
            image: dockersamples/examplevotingapp_result
            ports:
              - containerPort: 80
                name: vote
  selector:
    matchLabels:
      app: result-app
      tier: frontend
  replicas: 3

