apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      targetPort: voteport
      port: 80
  selector:
      app: vote-app
      tier: frontend
