apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote-app
    tier: frontend
spec:
  template:
     metadata:
        name: vote-app
        labels:
          app: vote-app
          tier: frontend
     spec:
        containers:
          - name: vote-app
            image: dockersamples/examplevotingapp_vote
            ports:
              - containerPort: 80
                name: vote
  selector:
    matchLabels:
      app: vote-app
      tier: frontend
  replicas: 3

